stages:
  - build
  - deploy

 
build_jar:
  stage: build
  only: 
  - master
  script:
  - mvn package
  tags:  
    - 'maven'
 
build_docker_image:
    stage: build
    variables:
      GIT_STRATEGY: none
    script:
     - docker info
     - docker login -u ${docker-username} -p ${docker-password} ${docker-server}
     - docker build -t registry.gitlab.com/emdoor/hello:$CI_PIPELINE_IID .
     - docker push registry.gitlab.com/emdoor/hello:$CI_PIPELINE_IID
    tags:  
     - 'maven' 

build_docker_compose:
    stage: build
    script:
      - sed -i s/docker-server/registry.gitlab.com/g ./docker-compose.yml
      - sed -i s/docker-org/emdoor/g ./docker-compose.yml
      - sed -i s/image-version/$CI_PIPELINE_IID/g ./docker-compose.yml

deploy_to_server:
    stage: deploy
    dependencies: 
    - build_docker_compose
    variables:
      GIT_STRATEGY: none
    script:
     - docker login -u ${docker-username} -p ${docker-password} ${docker-server}
     - docker-compose -f docker-compose.yml up -d
    tags:  
     - 'deploy'
